<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CloudinaryDotNet" Version="1.27.2" />
      <PackageReference Include="dotenv.net" Version="3.2.1" />
      <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common.Models\Common.Models.csproj" />
    </ItemGroup>

</Project>
